{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.bluesky.pds-dash;
  
  # Generate config.ts from NixOS configuration
  configFile = pkgs.writeText "config.ts" ''
    /**
     * Configuration module for the PDS Dashboard
     * Generated by NixOS configuration
     */
    export class Config {
      /**
       * The base URL of the PDS (Personal Data Server).
       */
      static readonly PDS_URL: string = "${cfg.settings.pdsUrl}";

      /**
       * Theme to be used
       */
      static readonly THEME: string = "${cfg.settings.theme}";

      /**
       * The base URL of the frontend service for linking to replies/quotes/accounts etc.
       */
      static readonly FRONTEND_URL: string = "${cfg.settings.frontendUrl}";

      /**
       * Maximum number of posts to fetch from the PDS per request
       */
      static readonly MAX_POSTS: number = ${toString cfg.settings.maxPosts};

      /**
       * Footer text for the dashboard. Supports HTML.
       */
      static readonly FOOTER_TEXT: string = "${cfg.settings.footerText}";

      /**
       * Whether to show the posts with timestamps that are in the future.
       */
      static readonly SHOW_FUTURE_POSTS: boolean = ${if cfg.settings.showFuturePosts then "true" else "false"};
    }
  '';
  
  # Create a startup script that sets up the environment
  startupScript = pkgs.writeShellScript "pds-dash-start" ''
    set -euo pipefail
    
    # Create working directory
    mkdir -p ${cfg.dataDir}
    cd ${cfg.dataDir}
    
    # Copy application files if not present or if package changed
    if [ ! -f .package-version ] || [ "$(cat .package-version)" != "${cfg.package.version}" ]; then
      echo "Setting up PDS Dashboard files..."
      rm -rf dist themes public package.json deno.lock
      cp -r ${cfg.package}/share/pds-dash/* .
      echo "${cfg.package.version}" > .package-version
    fi
    
    # Copy current configuration
    cp ${configFile} config.ts
    
    # Start the application
    exec ${pkgs.deno}/bin/deno task preview --host ${cfg.settings.host} --port ${toString cfg.settings.port}
  '';
in
{
  options.services.bluesky.pds-dash = {
    enable = mkEnableOption "PDS Dashboard web interface";

    package = mkOption {
      type = types.package;
      default = pkgs.witchcraft-systems-pds-dash or pkgs.pds-dash;
      defaultText = literalExpression "pkgs.pds-dash";
      description = "PDS Dashboard package to use";
    };

    dataDir = mkOption {
      type = types.path;
      default = "/var/lib/pds-dash";
      description = "Data directory for PDS Dashboard";
    };

    user = mkOption {
      type = types.str;
      default = "pds-dash";
      description = "User account for PDS Dashboard service";
    };

    group = mkOption {
      type = types.str;
      default = "pds-dash";
      description = "Group for PDS Dashboard service";
    };

    settings = mkOption {
      type = types.submodule {
        options = {
          pdsUrl = mkOption {
            type = types.str;
            example = "https://pds.example.com";
            description = "Base URL of the PDS to monitor";
          };

          host = mkOption {
            type = types.str;
            default = "127.0.0.1";
            description = "Host address to bind to";
          };

          port = mkOption {
            type = types.port;
            default = 3001;
            description = "Port to listen on";
          };

          theme = mkOption {
            type = types.str;
            default = "default";
            description = "Theme to use for the dashboard";
          };

          frontendUrl = mkOption {
            type = types.str;
            default = "https://bsky.app";
            example = "https://deer.social";
            description = "Base URL of the frontend service for linking";
          };

          maxPosts = mkOption {
            type = types.ints.positive;
            default = 20;
            description = "Maximum number of posts to fetch per request";
          };

          footerText = mkOption {
            type = types.str;
            default = "<a href='https://github.com/witchcraft-systems/pds-dash' target='_blank'>PDS Dashboard</a>";
            description = "Footer text for the dashboard (supports HTML)";
          };

          showFuturePosts = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to show posts with future timestamps";
          };

          openFirewall = mkOption {
            type = types.bool;
            default = false;
            description = "Whether to open the firewall for the dashboard port";
          };
        };
      };
      default = {};
      description = "PDS Dashboard configuration";
    };
  };

  config = mkIf cfg.enable {
    # Configuration validation
    assertions = [
      {
        assertion = cfg.settings.pdsUrl != "";
        message = "services.bluesky.pds-dash.settings.pdsUrl must be set";
      }
      {
        assertion = cfg.settings.port > 0 && cfg.settings.port < 65536;
        message = "services.bluesky.pds-dash.settings.port must be a valid port number (1-65535)";
      }
      {
        assertion = cfg.settings.maxPosts > 0;
        message = "services.bluesky.pds-dash.settings.maxPosts must be positive";
      }
    ];

    # User and group management
    users.users.${cfg.user} = {
      isSystemUser = true;
      group = cfg.group;
      home = cfg.dataDir;
      description = "PDS Dashboard service user";
    };

    users.groups.${cfg.group} = {};

    # Directory management using systemd tmpfiles
    systemd.tmpfiles.rules = [
      "d '${cfg.dataDir}' 0750 ${cfg.user} ${cfg.group} - -"
    ];

    # systemd service with security hardening
    systemd.services.pds-dash = {
      description = "PDS Dashboard web interface";
      wantedBy = [ "multi-user.target" ];
      after = [ "network.target" ];
      wants = [ "network.target" ];

      serviceConfig = {
        Type = "exec";
        User = cfg.user;
        Group = cfg.group;
        WorkingDirectory = cfg.dataDir;
        ExecStart = startupScript;
        Restart = "on-failure";
        RestartSec = "5s";

        # Security hardening
        NoNewPrivileges = true;
        ProtectSystem = "strict";
        ProtectHome = true;
        PrivateTmp = true;
        ProtectKernelTunables = true;
        ProtectKernelModules = true;
        ProtectControlGroups = true;
        RestrictSUIDSGID = true;
        RestrictRealtime = true;
        RestrictNamespaces = true;
        LockPersonality = true;
        MemoryDenyWriteExecute = false; # Deno needs this
        
        # File system access
        ReadWritePaths = [ cfg.dataDir ];
        ReadOnlyPaths = [ "/nix/store" ];
        
        # Network access
        RestrictAddressFamilies = [ "AF_INET" "AF_INET6" "AF_UNIX" ];
        
        # Capabilities
        CapabilityBoundingSet = [ "" ];
        AmbientCapabilities = [ "" ];
      };

      environment = {
        NODE_ENV = "production";
        DENO_DIR = "${cfg.dataDir}/.deno";
      };
    };

    # Firewall configuration
    networking.firewall.allowedTCPPorts = mkIf cfg.settings.openFirewall [ cfg.settings.port ];
  };
}