when:
  - event: ["push", "pull_request"]
    branch: ["feat-blsky-bsky-pkgs"]

engine: "nixery"

dependencies:
  nixpkgs:
    - nix

steps:
  - name: Build Nix packages
    command: |
      nix build .#default
